[package]
name = "pest-parse-demo"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio-stream = "0.1.16"
tokio = { version = "1", features = ["full", "test-util", "macros"] }
sapl-core = { version = "0.1.0", path = "../../sapl-core" }
