[package]
name = "embedded-pdp"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = "0.3.31"
notify = "8.0.0"
pest-parser = { version = "0.1.0", path = "../pest-parser" }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.115"
