[package]
name = "embedded-pdp"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = "0.3.31"
notify = "8.0.0"
sapl-core = { version = "0.1.0", path = "../sapl-core" }
pin-project-lite = "0.2.15"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.115"
